version: '3'

services:
  category:
    build: ./category
    restart: unless-stopped
    ports:
      - "1100:1100"
    networks:
      - app-network
    depends_on:
      - database
  gateway:
    build: ./gateway
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - app-network        
  location:
    build: ./location
    restart: unless-stopped
    ports:
      - "2200:2200"
    networks:
      - app-network
    depends_on:
      - database
  product:
    build: ./product
    restart: unless-stopped
    ports:
      - "3300:3300"
    networks:
      - app-network
    depends_on:
      - database
  supplier:
    build: ./supplier
    restart: unless-stopped
    ports:
      - "4400:4400"
    networks:
      - app-network
    depends_on:
      - database  
  supply:
    build: ./supply
    restart: unless-stopped
    ports:
      - "5500:5500"
    networks:
      - app-network
    depends_on:
      - database          
  user:
    build: ./user
    restart: unless-stopped
    ports:
      - "6600:6600"
    networks:
      - app-network
    depends_on:
      - database
  buildingFEIMS:
    build: ./buildingFEIMS
    restart: unless-stopped
    ports:
      - "8800:8800"
    networks:
      - app-network
    volumes:     
      - buildingdata:/usr/src/app/uploads   
    depends_on:
      - database
  siteFEIMS:
    build: ./siteFEIMS
    restart: unless-stopped
    ports:
      - "7700:7700"
    networks:
      - app-network
    volumes:     
      - sitedata:/usr/src/app/uploads  
    depends_on:
      - database
  database:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  buildingdata:
  sitedata: 