version: '3'

services:
  category:
    build: ./category
    restart: unless-stopped
    ports:
      - "1111:1111"
    networks:
      - app-network
    depends_on:
      - database
  gateway:
    build: ./gateway
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - app-network        
  location:
    build: ./location
    restart: unless-stopped
    ports:
      - "2222:2222"
    networks:
      - app-network
    depends_on:
      - database
  product:
    build: ./product
    restart: unless-stopped
    ports:
      - "3333:3333"
    networks:
      - app-network
    depends_on:
      - database
  supplier:
    build: ./supplier
    restart: unless-stopped
    ports:
      - "4444:4444"
    networks:
      - app-network
    depends_on:
      - database  
  supply:
    build: ./supply
    restart: unless-stopped
    ports:
      - "5555:5555"
    networks:
      - app-network
    depends_on:
      - database          
  user:
    build: ./user
    restart: unless-stopped
    ports:
      - "6666:6666"
    networks:
      - app-network
    depends_on:
      - database
  building:
    build: ./building
    restart: unless-stopped
    ports:
      - "7777:7777"
    networks:
      - app-network
    volumes:     
      - buildingdata:/usr/src/app/uploads   
    depends_on:
      - database
  cv:
    build: ./cv
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - database  
  low:
    build: ./low
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      - database 
  high:
    build: ./high
    restart: unless-stopped
    ports:
      - "9999:9999"
    networks:
      - app-network
    depends_on:
      - database        
  database:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  buildingdata:
